# permissions for end users to edit clusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-editor-role
rules:
- apiGroups:
  - infoscreen.opsboost.dev
  resources:
  - clusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - infoscreen.opsboost.dev
  resources:
  - clusters/status
  verbs:
  - get
