# permissions for end users to view firefoxes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: firefox-viewer-role
rules:
- apiGroups:
  - session.opsboost.dev
  resources:
  - firefoxes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - session.opsboost.dev
  resources:
  - firefoxes/status
  verbs:
  - get
