on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        uses: actions/setup-go@v3
        with:
          go-version: '1.19'
          check-latest: true
      - run: |
          go build
          ./infoscreen-operator --help
          mv infoscreen-operator iss-operator-amd64

      - name: Create archive
        run: |
          xz iss-operator-amd64

      - name: Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          automatic_release_tag: "latest"
          files: |
            iss-operator-amd64.xz
